import tkinter as tk
import os
import sys
import threading
from quantity_dialog import QuantityDialog
try:
    from PIL import Image, ImageTk
    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False

BG       = "#FFF8EE"
WHITE    = "#FFFFFF"
PRIMARY  = "#F5A623"
TEXT_DARK = "#3B1F0A"
TEXT_MUTED = "#B07840"
BORDER   = "#FFD966"
FONT_FAM = "Segoe UI"
FONT_BOLD  = (FONT_FAM, 12, "bold")
FONT_BODY  = (FONT_FAM, 12)
FONT_TITLE = (FONT_FAM, 14, "bold")

IMAGE_MAP = {
    "Nachos": "nachos.jpg",
    "Shawarma Rice": "shawarmarice.jpg",
    "Fries - Cheese": "fries.jpg",
    "Fries - Barbeque": "fries_bbq.png",
    "Fries - Sour and Cream": "fries_sourcream.png",
    "Takoyaki - Cheese (5pcs)": "takoyakicheese.jpg",
    "Takoyaki - Ham and Cheese (5pcs)": "takoyakihamcheese.jpg",
    "Takoyaki - Crab (5pcs)": "takoyakicrab.jpg",
    "Takoyaki - Overload (7pcs)": "takoyakioverload.jpg",
    "Chicken Tenders": "chickentenderscheese.jpg",
    "Sisig Silog": "sisigsilog.jpg",
    "Chicken silog": "chicksilog.jpg",
    "Sizzling Sisig (Rice Meal)": "sizzlingsisig.jpg",
    "Sizzling Tofu (Rice Meal)": "sizzlingtofu.png",
    "Sizzling Liempo (Rice Meal)": "sizzlingliempo.jpg",
    "Sizzling Sisig": "sizzlingsisig.jpg",
    "Sizzling Tofu": "sizzlingtofu.png",
    "Sizzling Liempo": "sizzlingliempo.jpg",
    "Sisig and Liempo": "sisig_liempo.png",
    "Sisig and Tofu": "tofu_sisig.png",
    "Sizzling Liempo and Tofu": "liempo_tofu.png",
    "Red Horse 1 Litro": "redhorse.jpg",
    "Alfonso Light": "alfonsolight.jpg",
    "Gin Bilog": "ginbilog.jpg",
    "Gin Kwatro": "ginkwatro.jpg",
    "Pale Pilsen": "palepilsen.png",
    "Chocolate Milk Tea": "Chocolate.png",
    "Chocolate Milk Tea 1 liter": "Chocolate.png",
    "Dark Chocolate Milk Tea": "Dark Chocolate.png",
    "Dark Chocolate Milk Tea 1 liter": "Dark Chocolate.png",
    "Taro Milk Tea": "Taro.png",
    "Taro Milk Tea 1 liter": "Taro.png",
    "Red Velvet Milk Tea": "RedVelvet.png",
    "Red Velvet Milk Tea 1 liter": "RedVelvet.png",
    "Matcha Milk Tea": "Matcha.png",
    "Matcha Milk Tea 1 liter": "Matcha.png",
    "Wintermelon Milk Tea": "Wintermelon.png",
    "Wintermelon Milk Tea 1 liter": "Wintermelon.png",
    "Cookies & Cream Milk Tea": "cookies&cream.png",
    "Cookies & Cream Milk Tea 1 liter": "cookies&cream.png",
    "White Bunny Milk Tea": "White bunny.png",
    "White Bunny Milk Tea 1 liter": "White bunny.png",
    "Mango Cheesecake Milk Tea": "Mangocheesecake.png",
    "Mango Cheesecake Milk Tea 1 liter": "Mangocheesecake.png",
    "Blue Lemonade Fruit Tea": "Blue lemonade .png",
    "Blue Lemonade Fruit Tea 1 liter": "Blue lemonade .png",
    "Blueberry Fruit Tea": "Blueberry.png",
    "Blueberry Fruit Tea 1 liter": "Blueberry.png",
    "Strawberry Fruit Tea": "Strawberry M.png",
    "Strawberry Fruit Tea 1 liter": "Strawberry M.png",
    "Green Apple Fruit Tea": "Green Apple.png",
    "Green Apple Fruit Tea 1 liter": "Green Apple.png",
    "Four Seasons Fruit Tea": "Four Seasons.png",
    "Four Seasons Fruit Tea 1 liter": "Four Seasons.png",
    "Lychee Fruit Tea": "Lychee.png",
    "Lychee Fruit Tea 1 liter": "Lychee.png",
    "Okinawa Milk Tea": "Okinawa.png",
    "Okinawa Milk Tea 1 liter": "Okinawa.png",
    "Strawberry Fruit Soda": "Strawberry.png",
    "Strawberry Fruit Soda 1 liter": "Strawberry.png",
    "Blueberry Fruit Soda": "Blueberry.png",
    "Blueberry Fruit Soda 1 liter": "Blueberry.png",
    "Green Apple Fruit Soda 1 liter": "Green Apple.png",
    "Green Apple Fruit Soda": "Green Apple.png",
    "Lychee Fruit Soda": "Lychee.png",
    "Lychee Fruit Soda 1 liter": "Lychee.png",
    "Blue Lemonade Fruit Soda": "Blue lemonade .png",
    "Blue Lemonade Fruit Soda 1 liter": "Blue lemonade .png",
    "Four Seasons Fruit Soda": "Four Seasons.png",
    "Four Seasons Fruit Soda 1 liter": "Four Seasons.png",
    "Pearl": "Pearl.png",
    "Nata De Coco": "Nata.png",
}
ASSETS_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "food @chizzlin")

# Handle PyInstaller bundled resources
if getattr(sys, 'frozen', False):
    # Running as compiled executable
    if hasattr(sys, '_MEIPASS'):
        # PyInstaller temp folder
        ASSETS_DIR = os.path.join(sys._MEIPASS, "assets", "food @chizzlin")
    else:
        # Fallback
        application_path = os.path.dirname(sys.executable)
        ASSETS_DIR = os.path.join(application_path, "assets", "food @chizzlin")
else:
    # Running as script
    ASSETS_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "food @chizzlin")


def _get_image_filename(name):
    """Return image filename: check IMAGE_MAP first, then try dynamic filename."""
    if name in IMAGE_MAP:
        return IMAGE_MAP[name]
    # Dynamic filename generated by AddProductWindow
    for ext in (".jpg", ".jpeg", ".png", ".gif", ".bmp"):
        candidate = name.lower().replace(" ", "_").replace("/", "-") + ext
        if os.path.exists(os.path.join(ASSETS_DIR, candidate)):
            return candidate
    return "no image.jpg"


# Fixed card image size — pre-rendered once, no resize on Configure
CARD_IMG_W = 160
CARD_IMG_H = 120


class ProductDisplay:
    def __init__(self, parent, pos_instance):
        self.parent     = parent
        self.pos        = pos_instance
        self._img_cache = {}
        self._preload_done = False
        self.create_product_panel()

    def preload_images(self, product_names):
        """Pre-load and resize all product images in a background thread."""
        def _load():
            for name in product_names:
                if not PIL_AVAILABLE:
                    break
                filename = _get_image_filename(name)
                path     = os.path.join(ASSETS_DIR, filename)
                key      = (path, CARD_IMG_W, CARD_IMG_H)
                if key in self._img_cache:
                    continue
                try:
                    pil_img = Image.open(path).convert("RGB")
                    iw, ih  = pil_img.size
                    scale   = max(CARD_IMG_W / iw, CARD_IMG_H / ih)
                    nw, nh  = int(iw * scale), int(ih * scale)
                    pil_img = pil_img.resize((nw, nh), Image.BILINEAR)
                    left    = (nw - CARD_IMG_W) // 2
                    top     = (nh - CARD_IMG_H) // 2
                    pil_img = pil_img.crop((left, top,
                                            left + CARD_IMG_W,
                                            top  + CARD_IMG_H))
                    # PhotoImage must be created on main thread
                    self.parent.after(0, lambda p=pil_img, k=key: self._store_photo(p, k))
                except Exception:
                    self._img_cache[key] = None
            self._preload_done = True
        threading.Thread(target=_load, daemon=True).start()

    def _store_photo(self, pil_img, key):
        """Called on main thread to safely create PhotoImage."""
        self._img_cache[key] = ImageTk.PhotoImage(pil_img)
    
    def _load_image_async(self, label, key, img_path):
        """Load image asynchronously if not in cache."""
        if key in self._img_cache:
            photo = self._img_cache[key]
            if photo:
                label.config(image=photo, text="")
                label.image = photo
            return
        
        try:
            pil_img = Image.open(img_path).convert("RGB")
            iw, ih  = pil_img.size
            scale   = max(CARD_IMG_W / iw, CARD_IMG_H / ih)
            nw, nh  = int(iw * scale), int(ih * scale)
            pil_img = pil_img.resize((nw, nh), Image.BILINEAR)
            left    = (nw - CARD_IMG_W) // 2
            top     = (nh - CARD_IMG_H) // 2
            pil_img = pil_img.crop((left, top,
                                    left + CARD_IMG_W,
                                    top  + CARD_IMG_H))
            photo   = ImageTk.PhotoImage(pil_img)
            self._img_cache[key] = photo
            label.config(image=photo, text="")
            label.image = photo
        except Exception:
            label.config(text="🍴", font=(FONT_FAM, 36), fg=TEXT_MUTED)

    def create_product_panel(self):
        panel = tk.Frame(self.parent, bg=BG)
        panel.pack(fill="both", expand=True, padx=(8, 8), pady=10)

        # Top row: count + search
        top_row = tk.Frame(panel, bg=BG)
        top_row.pack(fill="x", pady=(0, 6))

        self.prod_count_lbl = tk.Label(top_row, text="Products",
                                       font=FONT_TITLE, fg=TEXT_DARK, bg=BG)
        self.prod_count_lbl.pack(side="left", pady=6)

        # Search bar
        self.search_var = tk.StringVar()
        self._search_job = None
        self.search_var.trace("w", lambda *_: self._schedule_filter())

        search_outer = tk.Frame(top_row, bg=BORDER, padx=2, pady=2)
        search_outer.pack(side="right", pady=4)

        search_container = tk.Frame(search_outer, bg=WHITE)
        search_container.pack()

        tk.Label(search_container, text="🔍", bg=WHITE, fg=TEXT_MUTED,
                 font=(FONT_FAM, 11)).pack(side="left", padx=(10, 2), pady=0)

        self._search_entry = tk.Entry(
            search_container, textvariable=self.search_var,
            bg=WHITE, relief="flat", font=(FONT_FAM, 11),
            fg=TEXT_MUTED, insertbackground=TEXT_DARK,
            width=22, bd=0
        )
        self._search_entry.pack(side="left", ipady=7)
        self._search_entry.insert(0, "Search products...")

        clear_btn = tk.Label(search_container, text="✕", bg=WHITE,
                             fg=TEXT_MUTED, font=(FONT_FAM, 10),
                             cursor="hand2")
        clear_btn.pack(side="left", padx=(2, 10))
        clear_btn.bind("<Button-1>", lambda _: self._clear_search())

        self._search_entry.bind("<FocusIn>",
            lambda e: (self._on_search_focus_in(e),
                       search_outer.config(bg=PRIMARY)))
        self._search_entry.bind("<FocusOut>",
            lambda e: (self._on_search_focus_out(e),
                       search_outer.config(bg=BORDER)))

        tk.Frame(panel, bg=BORDER, height=2).pack(fill="x", pady=(0, 8))

        # Scrollable grid
        outer = tk.Frame(panel, bg=BG)
        outer.pack(fill="both", expand=True)

        self.prod_canvas = tk.Canvas(outer, bg=BG, highlightthickness=0)
        sb = tk.Scrollbar(outer, orient="vertical", command=self.prod_canvas.yview)
        self.prod_canvas.configure(yscrollcommand=sb.set)
        sb.pack(side="right", fill="y")
        self.prod_canvas.pack(side="left", fill="both", expand=True)

        self.prod_inner = tk.Frame(self.prod_canvas, bg=BG)
        self._prod_window = self.prod_canvas.create_window((0, 0), window=self.prod_inner, anchor="nw")

        self.prod_inner.bind("<Configure>",
                             lambda _: self.prod_canvas.configure(
                                 scrollregion=self.prod_canvas.bbox("all")))
        self.prod_canvas.bind("<Configure>",
                              lambda e: self.prod_canvas.itemconfig(self._prod_window, width=e.width))
        self.prod_canvas.bind("<Enter>",
                              lambda _: self.prod_canvas.bind_all("<MouseWheel>", self._on_scroll))
        self.prod_canvas.bind("<Leave>",
                              lambda _: self.prod_canvas.unbind_all("<MouseWheel>"))

    def _on_search_focus_in(self, e=None):
        if self.search_var.get() == "Search products...":
            self._search_entry.delete(0, "end")
            self._search_entry.config(fg=TEXT_DARK)

    def _on_search_focus_out(self, e=None):
        if not self.search_var.get() and self._search_entry.get() == "":
            self._search_entry.insert(0, "Search products...")
            self._search_entry.config(fg=TEXT_MUTED)

    def _clear_search(self):
        self._search_entry.delete(0, "end")
        self.search_var.set("")
        self._search_entry.insert(0, "Search products...")
        self._search_entry.config(fg=TEXT_MUTED)
        self._search_entry.master.focus()
        self.display_products(self.pos.products)

    def _open_qty_dialog(self, prod):
        QuantityDialog(self.parent, prod, self.pos.cart_manager, self._img_cache, pos=self.pos)

    def _on_scroll(self, e):
        self.prod_canvas.yview_scroll(-1 * (e.delta // 120), "units")

    def _schedule_filter(self):
        if self._search_job:
            self.parent.after_cancel(self._search_job)
        self._search_job = self.parent.after(150, self._filter)

    def _filter(self):
        q = self.search_var.get().lower()
        if q in ("", "search products..."):
            self.display_products(self.pos.products)
        else:
            self.display_products([p for p in self.pos.products if q in p[1].lower()])

    def display_products(self, products):
        for w in self.prod_inner.winfo_children():
            w.destroy()
        self.prod_canvas.yview_moveto(0)
        self.prod_count_lbl.config(text=f"Products  ({len(products)} items)")

        COLS = 5

        for idx, prod in enumerate(products):
            pid, name, price, *_ = prod
            row, col = divmod(idx, COLS)

            card = tk.Frame(self.prod_inner, bg=WHITE, cursor="hand2",
                            highlightbackground=BORDER, highlightthickness=2)
            card.grid(row=row, column=col, padx=6, pady=6, sticky="nsew")
            self.prod_inner.grid_columnconfigure(col, weight=1, uniform="col")

            # Cover-fit image
            img_frame = tk.Frame(card, bg=BG, width=CARD_IMG_W, height=CARD_IMG_H)
            img_frame.pack(fill="x")
            img_frame.pack_propagate(False)

            img_label = tk.Label(img_frame, bg=BG, borderwidth=0)
            img_label.place(relx=0.5, rely=0.5, anchor="center")

            if PIL_AVAILABLE:
                filename = _get_image_filename(name)
                img_path = os.path.join(ASSETS_DIR, filename)
                key      = (img_path, CARD_IMG_W, CARD_IMG_H)
                photo    = self._img_cache.get(key)
                if photo:
                    img_label.config(image=photo)
                    img_label.image = photo
                else:
                    # Show placeholder while loading
                    img_label.config(text="⏳", font=(FONT_FAM, 36), fg=TEXT_MUTED)
                    # Schedule image load
                    self.parent.after(10, lambda lbl=img_label, k=key, p=img_path: self._load_image_async(lbl, k, p))
            else:
                img_label.config(text="🍴", font=(FONT_FAM, 36), fg=TEXT_MUTED)

            # Info strip
            info = tk.Frame(card, bg=WHITE, padx=8, pady=6)
            info.pack(fill="x")
            tk.Label(info, text=name, font=(FONT_FAM, 10, "bold"), fg=TEXT_DARK, bg=WHITE,
                     wraplength=120, justify="left", anchor="w").pack(fill="x")
            tk.Label(info, text=f"₱{price:,.2f}", font=(FONT_FAM, 11, "bold"),
                     fg=TEXT_DARK, bg=WHITE, anchor="w").pack(fill="x", pady=(2, 6))

            add_btn = tk.Label(card, text="+ Add", font=(FONT_FAM, 10, "bold"),
                               fg=WHITE, bg=PRIMARY, pady=6)
            add_btn.pack(fill="x", side="bottom")

            HOVER_BG  = "#FFF0D0"
            HOVER_BTN = "#E8920A"

            all_widgets = [card, img_frame, img_label, info] + list(info.winfo_children())
            
            # Debounce hover events to prevent flickering during scroll
            hover_job = {'id': None}

            def _on_enter(e, c=card, ws=all_widgets, ab=add_btn, job=hover_job):
                if job['id']:
                    c.after_cancel(job['id'])
                job['id'] = c.after(50, lambda: _apply_hover(c, ws, ab, job))

            def _apply_hover(c, ws, ab, job):
                job['id'] = None
                c.config(highlightbackground=PRIMARY, bg=HOVER_BG)
                for w in ws:
                    try: w.config(bg=HOVER_BG)
                    except tk.TclError: pass
                ab.config(bg=HOVER_BTN)
                img_frame.config(bg=BG)
                img_label.config(bg=BG)

            def _on_leave(e, c=card, ws=all_widgets, ab=add_btn, job=hover_job):
                if job['id']:
                    c.after_cancel(job['id'])
                    job['id'] = None
                c.config(highlightbackground=BORDER, bg=WHITE)
                for w in ws:
                    try: w.config(bg=WHITE)
                    except tk.TclError: pass
                ab.config(bg=PRIMARY)
                img_frame.config(bg=BG)
                img_label.config(bg=BG)

            for widget in all_widgets + [add_btn]:
                widget.bind("<Button-1>", lambda _, p=prod: self._open_qty_dialog(p))
                widget.bind("<Enter>", _on_enter)
                widget.bind("<Leave>", _on_leave)
